version: "3.7"

services:
  nginx:
    image: nginx:1.19
    depends_on:
      - php
      - mysql
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  
  artisan:
    build: .
    container_name: artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    # this entry point will works after you install the laravel project,
    # if the project already exists turn this line on.
    # entrypoint: ["/var/www/html/artisan"]


  node:
    image: node:14.17.0
    container_name: node
    volumes: 
        - .:/var/www/html
    working_dir: /var/www/html
    # entrypoint: ["npm"]

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      # MYSQL_USER: "${DB_USERNAME}"
