version: "3.7"

volumes: 
    mysqldbvolume:
        driver: local

services:
    nginx:
        image: nginx:1.19
        container_name: nginx
        depends_on:
            - php
            - mysql
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: .
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"

    node:
        image: node:14.17.0
        container_name: node
        working_dir: /var/www/html
        volumes: 
            - .:/var/www/html
        # entrypoint: ["npm"]

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes: 
            - mysqldbvolume:/var/lib/mysql
        environment:
            # MYSQL_ALLOW_EMPTY_PASSWORD: 1
            # MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: my_dbname
            # MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
